spring:
  application:
    name: hhplus
  profiles:
    active: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  task:
    scheduling:
      enabled: false